version: '3.8'

services:
  postgres:
    platform: linux/amd64
    image: postgres:16-alpine
    container_name: link_shortener_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=shortener
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      app-network:
        aliases:
          - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shortener"]
      interval: 5s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7-alpine
    container_name: link_shortener_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      app-network:
        aliases:
          - redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 5

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    container_name: link_shortener_migrate
    volumes:
      - ./migrations:/migrations
    command: -path=/migrations -database "postgres://postgres:12345@postgres:5432/shortener?sslmode=disable" up
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: link_shortener_app
    ports:
      - "8080:8080"
    env_file:
      - ./configs/.env
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

volumes:
  pgdata:
  redisdata:

networks:
  app-network:
    driver: bridge
