// Code generated by MockGen. DO NOT EDIT.
// Source: link.go
//
// Generated by this command:
//
//	mockgen -source=link.go -destination=mocks/mock_store.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockLinkStore is a mock of LinkStore interface.
type MockLinkStore struct {
	ctrl     *gomock.Controller
	recorder *MockLinkStoreMockRecorder
	isgomock struct{}
}

// MockLinkStoreMockRecorder is the mock recorder for MockLinkStore.
type MockLinkStoreMockRecorder struct {
	mock *MockLinkStore
}

// NewMockLinkStore creates a new mock instance.
func NewMockLinkStore(ctrl *gomock.Controller) *MockLinkStore {
	mock := &MockLinkStore{ctrl: ctrl}
	mock.recorder = &MockLinkStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkStore) EXPECT() *MockLinkStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockLinkStore) Get(ctx context.Context, code string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, code)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLinkStoreMockRecorder) Get(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLinkStore)(nil).Get), ctx, code)
}

// IncrementClicks mocks base method.
func (m *MockLinkStore) IncrementClicks(ctx context.Context, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementClicks", ctx, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementClicks indicates an expected call of IncrementClicks.
func (mr *MockLinkStoreMockRecorder) IncrementClicks(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementClicks", reflect.TypeOf((*MockLinkStore)(nil).IncrementClicks), ctx, code)
}

// Save mocks base method.
func (m *MockLinkStore) Save(ctx context.Context, code, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, code, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockLinkStoreMockRecorder) Save(ctx, code, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockLinkStore)(nil).Save), ctx, code, url)
}

// MockLinkCache is a mock of LinkCache interface.
type MockLinkCache struct {
	ctrl     *gomock.Controller
	recorder *MockLinkCacheMockRecorder
	isgomock struct{}
}

// MockLinkCacheMockRecorder is the mock recorder for MockLinkCache.
type MockLinkCacheMockRecorder struct {
	mock *MockLinkCache
}

// NewMockLinkCache creates a new mock instance.
func NewMockLinkCache(ctrl *gomock.Controller) *MockLinkCache {
	mock := &MockLinkCache{ctrl: ctrl}
	mock.recorder = &MockLinkCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkCache) EXPECT() *MockLinkCacheMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockLinkCache) Delete(ctx context.Context, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLinkCacheMockRecorder) Delete(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLinkCache)(nil).Delete), ctx, code)
}

// Get mocks base method.
func (m *MockLinkCache) Get(ctx context.Context, code string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, code)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLinkCacheMockRecorder) Get(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLinkCache)(nil).Get), ctx, code)
}

// Set mocks base method.
func (m *MockLinkCache) Set(ctx context.Context, code, url string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, code, url, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockLinkCacheMockRecorder) Set(ctx, code, url, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockLinkCache)(nil).Set), ctx, code, url, ttl)
}
